-- Constituent campuses of Tribhuvan University
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Mahendra Ratna Multiple Campus, Illam');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Gaurahadaha Agriculture Campus, Jhapa');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Mechi Multiple Campus, Jhapa');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Mahendra Morang Adarsh Multiple Campus, Biratnagar');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Snatakottar Campus (Postgraduate Campus), Biratnagar');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Nursing Campus, Biratnagar');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Purbanchal Campus, Dharan');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Mahendra Multiple Campus, Dharan');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Central Campus of Technology, Dharan');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Dhankuta Multiple Campus, Dhankuta');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Tehrathum Multiple Campus, Terhathum');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Bhojpur Multiple Campus, Bhojpur');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Ramshwaroop Ramsagar Multiple Campus, Janakpur');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Thakur Ram Multiple Campus, Birgunj');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Birgunj Nursing Campus, Birgunj');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Surya Narayana Satya Narayana Morveta Yadhav Multiple Campus, Siraha');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Mahendra Bindeshwori Multiple Campus, Saptari');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Hetauda Forestry Campus, Hetauda');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Rampur Agriculture Campus, Chitwan');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Chitwan Engineering Campus, Chitwan');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Birendra Multiple Campus, Chitwan');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Nepal Commerce Campus, Minbhavan, Kathmandu');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Sanothimi Campus, Bhaktapur');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Bhaktapur Multiple Campus, Bhaktapur');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Patan Samyukta Campus, Patandhoka');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Pulchowk Campus, Pulchowk');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Nepal Commerce Campus, Min Bhawan');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Thapathali Campus, Thapathali');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Jana Prasashan Campus, Balkhu');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, University Campus, Kirtipur');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Mahendra Ratna Campus, Tahachal');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Ayurved Campus, Kirtipur');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Public Youth Campus, Dhobichaur');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Saraswoti Multiple Campus, Lainchaur');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Amrit Campus, Lainchaur');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Central Medicine Campus, Maharajgung');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Nursing Campus, Maharajgunj');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Lalitkala Campus, Bhotahiti');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Trichandra Multiple Campus, Ghantaghar');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Padmakanya Multiple Campus, Bagbazar');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Shanker Dev Campus, Putalisadak');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Ratna Rajya Lakshmi Campus, Pradarshani Marg, Kathmandu');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Nepal Law Campus, Pradarshani Marg');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Bishwa Bhasa Campus, Pradarshani Marg');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Paschimanchal Campus, Pokhara');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Gorkha Campus, Gorkha');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Lamjung Agriculture Campus, Sundarbazar');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Dhaulagiri Campus, Baglung');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Pokhara Nursing Campus, Pokhara');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Pokhara Forestry Campus, Pokhara');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Prithivi Narayan Campus, Pokhara');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Tribhuwan Multiple Campus, Syangja');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Tribhuvan Multiple Campus, Palpa');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Butwal Multiple Campus, Butwal');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Paklihawa Agriculture Campus, Paklihawa');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Bhairahawa Multiple Campus, Bhairahawa');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Mahendra Multiple Campus, Dang');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Mahendra Multiple Campus, Nepalgunj');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, mahakavi devkota campus, sunwal');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Surkhet Multiple Campus, Birendranagar');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Jumla Multiple Campus, Jumla');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Musikot Multiple Campus, Rukum');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Doti Multiple Campus, Doti');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Dadeldhura Campus, Dadeldhura');
INSERT INTO academic_institution (institution_name) VALUES ('Tribhuvan University, Siddhanath Science Campus, Mahendranagar');
